Repository mxcl/swift-sh, pull requests merged in 2019-02, with the labels that each got.

#41 Fix support for exactly-specified dependency versions
  Sources/Library/ImportSpecification.swift
Labels: merge when passing, patch

#43 Add tests for exact and revsion specifications
  Package.resolved
  Sources/Library/ImportSpecification.swift
  Tests/ShwiftyTests/IntegrationTests.swift
  Tests/ShwiftyTests/XCTestManifests.swift
Labels: merge when passing

#49 Tidy
  Package.resolved
  Package.swift
  Sources/Command/CommandLine.usage.swift
  Sources/Command/eject().swift
  Sources/Command/run().swift
  Sources/Library/String+RegExp.swift
  Sources/Library/Version.swift
  Sources/Script/ImportSpecification.swift
  Sources/Script/Script.swift
  Sources/Script/parse().swift
  Sources/Utility/Process+1up.swift
  Sources/Utility/StreamReader.swift
  Sources/Utility/TemporaryDirectory.swift
  Sources/Utility/etc.swift
  Sources/main.swift
  Tests/All/IntegrationTests.swift
  Tests/All/UnitTests.swift
  Tests/All/UtilityTests.swift
  Tests/All/XCTestManifests.swift
  Tests/LinuxMain.swift
Labels: merge when passing

#50 Line number sync
  Package@swift-5.0.swift
  Sources/Command/run().swift
Labels: merge when passing, patch

#51 Fix linux swift 5
  Sources/Script/Script.swift
  Tests/All/IntegrationTests.swift
  Tests/All/UnitTests.swift
  Tests/All/XCTestManifests.swift
Labels: merge when passing, patch

#55 Swift sh edit
  README.md
  Sources/Command/CommandLine.usage.swift
  Sources/Command/edit().swift
  Sources/Command/eject().swift
  Sources/Command/run().swift
  Sources/Script/ImportSpecification.swift
  Sources/Script/Script.swift
  Sources/Script/parse().swift
  Sources/Utility/etc.swift
  Sources/Utility/exec().swift
  Sources/main.swift
  Tests/All/IntegrationTests.swift
Labels: merge when passing, minor

#58 Fix swift sh edit so it can save
  .travis.yml
  Package.resolved
  Package.swift
  Sources/Command/edit().swift
  Sources/Script/Script.swift
  Sources/Utility/exec().swift
  Sources/main.swift
  Sources/swift-sh-edit/main.swift
Labels: merge when passing, patch

#61 `import Foo // @bar` picks the latest version
  .travis.yml
  README.md
  Sources/Script/ImportSpecification.swift
  Sources/Script/parse().swift
  Sources/Utility/etc.swift
  Tests/All/IntegrationTests.swift
  Tests/All/UnitTests.swift
  Tests/All/XCTestManifests.swift
Labels: merge when passing, minor

#63 Process subst
  .travis.yml
  Sources/Command/run().Input.swift
  Sources/Command/run().swift
  Sources/Utility/Process+1up.swift
  Sources/Utility/StreamReader.swift
  Sources/main.swift
  Tests/All/IntegrationTests.swift
  Tests/All/XCTestManifests.swift
Labels: merge when passing, patch

#65 Enum OptionParser; fixes some edge cases
  Sources/Command/CommandLine.usage.swift
  Sources/Command/edit().swift
  Sources/Command/eject().swift
  Sources/Command/run().Input.swift
  Sources/Command/run().swift
  Sources/Utility/StreamReader.swift
  Sources/main.swift
  Tests/All/ImportSpecificationUnitTests.swift
  Tests/All/ModeUnitTests.swift
  Tests/All/XCTestManifests.swift
Labels: merge when passing, patch
